### ISSUE TITLE
No Filterscripts and Include in server.cfg

### ISSUE THREAD

**Issue by ghost** [LVPlayground/server#2]
> filterscripts cake drop_radio

**Comment by mblokker** [comment]
Hi, can you clarify?

**Comment by ghost** [comment]
those filterscripts not commited in 

> Server/Filterscripts

and Commited in 

Server.cfg

**Comment by mblokker** [comment]
The filterscripts ignored by git thanks to the https://github.com/LVPlayground/server/blob/master/filterscripts/.gitignore file.

There are plans to incorporate the filterscripts into the LVP gamemode, which by then they will become open-source. For now, they are not added due to instability (my filterscript is mainly used for debugging and testing on the fly).

Hope this answers your sort-of question.
